---
- name: Gather Ansible facts
  setup:

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
        
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  
- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: 'add users to docker group'
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  with_items: 'oenctester'

- name: Ensures /etc/systemd/system/docker.service.d dir exists
  file: path=/etc/systemd/system/docker.service.d state=directory
  
- name: 'prepare default docker http-proxy configuration'
  copy:
    src: 'http-proxy.conf'
    dest: '/etc/systemd/system/docker.service.d/http-proxy.conf'
  
- name: 'prepare default daemon configuration'
  copy:
    src: 'daemon.json'
    dest: '/etc/docker/daemon.json'
  
- name: 'restart and enable docker systemd service'
  service:
    name: 'docker'
    state: 'restarted'
    enabled: 'yes'
    
- name: Add SGX GPG apt Key
  apt_key:
    url: https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
    state: present

- name: Add SGX Repository
  apt_repository:
    repo: deb https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main
    state: present

- name: Update apt and install libsgx-enclave-common libsgx-urts sgx-aesm-service libsgx-uae-service autoconf libtool make gcc libprotobuf-dev
  apt:
    name:
      - libsgx-enclave-common
      - libsgx-urts
      - sgx-aesm-service
      - libsgx-uae-service
      - autoconf
      - libtool
      - make
      - gcc
      - libprotobuf-dev
    state: latest
    update_cache: yes
    install_recommends: no
  
